[technote]
id = "DMTN-021"
series_id = "DMTN"
canonical_url = "https://dmtn-021.lsst.io/"
github_url = "https://github.com/lsst-dm/dmtn-021"
github_default_branch = "main"
organization.name = "Vera C. Rubin Observatory"
organization.ror = "https://ror.org/048g3cy84"
license.id = "CC-BY-4.0"
date_created = 2016-06-14T00:03:48Z
date_updated = 2016-12-05T18:52:15Z
doi = "https://doi.org/10.71929/rubin/2586490"
[[technote.authors]]
name = {given = "David J.", family = "Reiss"}
internal_id = "reissdj"
[[technote.authors.affiliations]]
name = "University of Washington"
internal_id = "Washington"
ror = "https://ror.org/00cvxb145"

[[technote.authors]]
name = {given = "Robert H.", family = "Lupton"}
internal_id = "luptonrh"
orcid = "https://orcid.org/0000-0003-1666-0962"
[[technote.authors.affiliations]]
name = "Princeton University"
internal_id = "Princeton-Astro"
ror = "https://ror.org/00hx57361"
